version: '3'

services:
  web:
    image: nginx:latest
    depends_on:
      - wordpress
    ports:
      - 8443:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - wordpress:/var/www/html
    networks:
      - wordpress

  wordpress:
    image: wordpress:php8.2-fpm-alpine
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER_FILE: /run/secrets/mysql_user
      WORDPRESS_DB_NAME: wp_database
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/mysql_password
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/html
    networks:
      - wordpress
    secrets:
      - mysql_user
      - mysql_password

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: mysql_password
      MYSQL_DATABASE: wp_database
      MYSQL_USER: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/mysql
    networks:
        - wordpress
volumes:
   wordpress:
   dbdata:
networks:
   wordpress:
     name: wordpress
     driver: overlay

# external: true telling compose secrets are already created and not to create a new one.
# secrets will have to be created before running compose.
secrets:
  mysql_user:
    external: true
  mysql_password:
    external: true
